param ($lang, $fallback = "en")

$langs = @{
"sq" = "albanian"
"am" = "amharic"
"ar" = "arabic"
"hy" = "armenian"
"eu" = "basque"
"bn" = "bengali"
"br" = "breton"
"bg" = "bulgarian"
"ca" = "catalan"
"hr" = "croation"
"cs" = "czech"
"da" = "danish"
"nl" = "dutch"
"en" = "english"
"eo" = "esperanto"
"et" = "estonian"
"fa" = "farsi"
"fi" = "finnish"
"fr" = "french"
"gl" = "galician"
"de" = "german"
"el" = "greek"
"he" = "hebrew"
"iw" = "hebrew"
"hi" = "hindi"
"is" = "icelandic"
"ia" = "interlingua"
"ga" = "irish"
"it" = "italian"
"kn" = "kannada"
"lo" = "lao"
"la" = "latin"
"lv" = "latvian"
"lt" = "lithuanian"
"ml" = "malayalam"
"mr" = "marathi"
"oc" = "occitan"
"pl" = "polish"
"pt" = "portuges"
"ro" = "romanian"
"ru" = "russian"
"sa" = "sanskrit"
"sr" = "serbian"
"sk" = "slovak"
"sl" = "slovenian"
"es" = "spanish"
"sv" = "swedish"
"ta" = "tamil"
"te" = "telugu"
"bo" = "tibetan"
"th" = "thai"
"tr" = "turkish"
"tk" = "turkmen"
"uk" = "ukrainian"
"ur" = "urdu"
"vi" = "vietnamese"
"cy" = "welsh"
}

if ($langs.Keys -contains $lang) {
	return $langs[$lang]
} else {
	return $lang[$fallback]
}
